package com.mehmetakiftutuncu.eshotroid.model;

import android.content.ContentValues;
import android.database.Cursor;

import com.mehmetakiftutuncu.eshotroid.provider.EshotroidProvider;

/** A model class for a Kent Kart
 * 
 * @author mehmetakiftutuncu */
public class KentKart
{
	private int id;
	private String name;
	private String aliasNo1;
	private String aliasNo2;
	private String aliasNo3;
	
	public KentKart(int id, String name, String aliasNo1, String aliasNo2, String aliasNo3)
	{
		setId(id);
		setName(name);
		setAliasNo1(aliasNo1);
		setAliasNo2(aliasNo2);
		setAliasNo3(aliasNo3);
	}
	
	public KentKart(String name, String aliasNo1, String aliasNo2, String aliasNo3)
	{
		this(0, name, aliasNo1, aliasNo2, aliasNo3);
	}
	
	public int getId()
	{
		return id;
	}
	
	public void setId(int id)
	{
		this.id = id;
	}
	
	public String getName()
	{
		return name;
	}
	
	public void setName(String name)
	{
		this.name = name;
	}
	
	public String getAliasNo1()
	{
		return aliasNo1;
	}
	
	public void setAliasNo1(String aliasNo1)
	{
		this.aliasNo1 = aliasNo1;
	}
	
	public String getAliasNo2()
	{
		return aliasNo2;
	}
	
	public void setAliasNo2(String aliasNo2)
	{
		this.aliasNo2 = aliasNo2;
	}
	
	public String getAliasNo3()
	{
		return aliasNo3;
	}
	
	public void setAliasNo3(String aliasNo3)
	{
		this.aliasNo3 = aliasNo3;
	}
	
	/**
	 * Converts this Kent Kart to a ContentValues package
	 * 
	 * @return A ContentValues package having the values as attributes of this Kent Kart
	 */
	public ContentValues toContentValues()
	{
		ContentValues values = new ContentValues();
		
		values.put(EshotroidProvider.KentKarts.COLUMN_ID, getId());
		values.put(EshotroidProvider.KentKarts.COLUMN_NAME, getName());
		values.put(EshotroidProvider.KentKarts.COLUMN_ALIAS1, getAliasNo1());
		values.put(EshotroidProvider.KentKarts.COLUMN_ALIAS2, getAliasNo2());
		values.put(EshotroidProvider.KentKarts.COLUMN_ALIAS3, getAliasNo3());
		
		return values;
	}
	
	/**
	 * Converts given Cursor to a Kent Kart
	 * 
	 * @param cursor Cursor generated by a query
	 * 
	 * @return KentKart generated by the values read from the cursor
	 */
	public static KentKart fromCursor(Cursor cursor)
	{
		if(cursor != null && cursor.getCount() > 0)
		{
			int id = cursor.getInt(cursor.getColumnIndex(EshotroidProvider.KentKarts.COLUMN_ID));
			String name = cursor.getString(cursor.getColumnIndex(EshotroidProvider.KentKarts.COLUMN_NAME));
			String aliasNo1 = cursor.getString(cursor.getColumnIndex(EshotroidProvider.KentKarts.COLUMN_ALIAS1));
			String aliasNo2 = cursor.getString(cursor.getColumnIndex(EshotroidProvider.KentKarts.COLUMN_ALIAS2));
			String aliasNo3 = cursor.getString(cursor.getColumnIndex(EshotroidProvider.KentKarts.COLUMN_ALIAS3));
			
			return new KentKart(id, name, aliasNo1, aliasNo2, aliasNo3);
		}
		
		return null;
	}
	
	@Override
	public String toString()
	{
		if(name == null || name.equals(""))
		{
			return aliasNo1 + " " + aliasNo2 + " " + aliasNo3;
		}
		
		return name + " - " + aliasNo1 + " " + aliasNo2 + " " + aliasNo3;
	}
}